language: java
jdk:
- oraclejdk8
before_install:
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')
before_script:
- chmod +x gradlew
script:
- ./gradlew check
- ./gradlew jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r processor/build/reports/jacoco/test/jacocoTestReport.xml