name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1      
    - name: Build
      uses: MrRamych/gradle-actions/openjdk-8@2.1
      with: 
        args: '"
        build
        "'
