name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Android build action
      uses: xdtianyu/actions-android-ci@v1.0.0
      with: 
        args: '"
        ./gradlew build
        "'
