name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1      
    - name: Build & Generate Jacoco Report
      uses: MrRamych/gradle-actions/openjdk-8@2.1
      with: 
        args: '"
        build jacocoTestReport
        "'
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./processor/build/reports/jacoco/test/jacocoTestReport.xml
